[ITA-227] Add option to build with Ubuntu 14.04

diff --git a/jvm-packages/jenkins/Jenkinsfile-Release b/jvm-packages/jenkins/Jenkinsfile-Release
--- a/jvm-packages/jenkins/Jenkinsfile-Release
+++ b/jvm-packages/jenkins/Jenkinsfile-Release
@@ -5,8 +5,11 @@ import ai.h2o.ci.BuildResult
 import ai.h2o.ci.buildsummary.DetailsSummary
 import ai.h2o.ci.buildsummary.StagesSummary
 
+CENTOS_6 = 'centos6'
+UBUNTU_14 = 'ubuntu14'
+
 PUBLISHABLE_BRANCH_NAME = 'h2o3'
-IMAGES_MAP = ['centos6']
+IMAGES_MAP = [CENTOS_6, UBUNTU_14]
 
 // initialize build summary
 buildSummary('https://github.com/h2oai/xgboost', true)
@@ -25,28 +28,20 @@ def dockerImage = null
 def configurations = null
 
 final Map CHECK_IMAGES = [
-        minimal: [
-                [name: 'CentOS 6', dockerImage: "${REGISTRY}/opsh2oai/h2o-3-xgboost-build-centos6", os: 'linux'],
-                [name: 'Ubuntu 16', dockerImage: "${REGISTRY}/opsh2oai/h2o-3-runtime:107", os: 'linux'],
-                [name: 'OS X', os: 'osx', node: 'osx']
-        ],
-        omp    : [
-                [name: 'CentOS 6', dockerImage: "${REGISTRY}/opsh2oai/h2o-3-xgboost-build-centos6", os: 'linux'],
-                [name: 'Ubuntu 16', dockerImage: "${REGISTRY}/opsh2oai/h2o-3-runtime:107", os: 'linux'],
-        ],
-        gpu    : [
-                [name: 'CentOS 6', dockerImage: "${REGISTRY}/opsh2oai/h2o-3-xgboost-build-centos6", os: 'linux'],
-                [name: 'Ubuntu 16', dockerImage: "${REGISTRY}/opsh2oai/h2o-3-runtime:107", os: 'linux'],
-        ]
-
+    minimal: [
+        [name: 'CentOS 6', dockerImage: "${REGISTRY}/opsh2oai/h2o-3-xgboost-build-centos6", os: 'linux'],
+        [name: 'Ubuntu 16', dockerImage: "${REGISTRY}/opsh2oai/h2o-3-runtime:107", os: 'linux'],
+        [name: 'OS X', os: 'osx', node: 'osx']
+    ],
+    omp: [
+        [name: 'CentOS 6', dockerImage: "${REGISTRY}/opsh2oai/h2o-3-xgboost-build-centos6", os: 'linux'],
+        [name: 'Ubuntu 16', dockerImage: "${REGISTRY}/opsh2oai/h2o-3-runtime:107", os: 'linux'],
+    ],
+    gpu: [
+        [name: 'CentOS 6', dockerImage: "${REGISTRY}/opsh2oai/h2o-3-xgboost-build-centos6", os: 'linux'],
+        [name: 'Ubuntu 16', dockerImage: "${REGISTRY}/opsh2oai/h2o-3-runtime:107", os: 'linux'],
+    ]
 ]
-
-// setup custom DetailsSummary
-DetailsSummary detailsSummary = new DetailsSummary()
-detailsSummary.setEntry(this, 'Build OS', "${params.targetOS} + OS X")
-detailsSummary.setEntry(this, 'Publish', params.publish ? 'Yes' : 'No')
-detailsSummary.setEntry(this, 'Docker image', dockerImage)
-buildSummary.get().addDetailsSummary(this, detailsSummary)
 
 // use default StagesSummary implementation
 buildSummary.get().addStagesSummary(this, new StagesSummary())
@@ -67,6 +62,13 @@ try {
                 [name: 'gpu', useCuda: true, useOmp: true, os: 'linux', dockerImage: dockerImage],
                 [name: 'minimal', useCuda: false, useOmp: false, os: 'osx', node: 'osx'],
             ]
+            
+            // setup custom DetailsSummary
+            DetailsSummary detailsSummary = new DetailsSummary()
+            detailsSummary.setEntry(this, 'Build OS', "${params.targetOS} + OS X")
+            detailsSummary.setEntry(this, 'Publish', params.publish ? 'Yes' : 'No')
+            detailsSummary.setEntry(this, 'Docker image', dockerImage)
+            buildSummary.get().addDetailsSummary(this, detailsSummary)
 
             sh 'git submodule update --init --recursive'
             withCredentials([usernamePassword(credentialsId: REGISTRY, usernameVariable: 'REGISTRY_USERNAME', passwordVariable: 'REGISTRY_PASSWORD')]) {
@@ -114,7 +116,7 @@ try {
                         }
                     }
                 } finally {
-                    archiveArtifacts artifacts: 'ci_build/*.jar', allowEmptyArchive: true
+                    archiveArtifacts artifacts: 'ci_build/*.jar,**/build-log-*.log,**/ldd_check_*.log', allowEmptyArchive: true
                 }
             }
         }
@@ -225,7 +227,13 @@ private void executeBuild(final config) {
 private String getBuildScript(final String os, final boolean useCuda, final boolean useOmp) {
     switch (os) {
         case 'linux':
-            return getCentOS6BuildScript(useCuda, useOmp)
+            if (params.targetOS == CENTOS_6) {
+                return getCentOS6BuildScript(useCuda, useOmp)
+            }
+            if (params.targetOS == UBUNTU_14) {
+                return getUbuntu14BuildScript(useCuda, useOmp)
+            }
+            error "targetOS ${params.targetOS} not supported"
         case 'osx':
             return getOSXBuildScript(useCuda, useOmp)
         default:
@@ -253,6 +261,20 @@ private String getCentOS6BuildScript(final boolean useCuda, final boolean useOmp
     """
 }
 
+private String getUbuntu14BuildScript(final boolean useCuda, final boolean useOmp) {
+    return """
+        export JAVA_HOME=/usr/lib/jvm/java-8-oracle
+        if [ "\$(cmake --version | head -1)" != 'cmake version 3.5.2' ]; then 
+            echo "UNEXPECTED CMAKE VERSION"
+            cmake --version
+            exit 1; 
+        fi
+
+        cmake .. ${getCMakeOpts(useCuda, useOmp)}
+        make
+    """
+}
+
 private String getOSXBuildScript(final boolean useCuda, final boolean useOmp) {
     return """
         export JAVA_HOME=\$(/usr/libexec/java_home)
@@ -265,7 +287,13 @@ private String getOSXBuildScript(final boolean useCuda, final boolean useOmp) {
 private String getJvmPackagesBuildScript(final String os, final boolean useCuda, final boolean useOmp) {
     switch (os) {
         case 'linux':
-            return getCentOS6JvmPackagesBuildScript(useCuda, useOmp)
+            if (params.targetOS == CENTOS_6) {
+                return getCentOS6JvmPackagesBuildScript(useCuda, useOmp)
+            }
+            if (params.targetOS == UBUNTU_14) {
+                return getUbuntu14JvmPackagesBuildScript(useCuda, useOmp)
+            }
+            error "targetOS ${params.targetOS} not supported"
         case 'osx':
             return getOSXJvmPackagesBuildScript(useCuda, useOmp)
         default:
@@ -282,6 +310,13 @@ private String getCentOS6JvmPackagesBuildScript(final boolean useCuda, final boo
             echo "UNEXPECTED PYTHON VERSION"
             python --version
         fi
+        ${getBuildJARsOpts(useCuda, useOmp)} ./build_jars.sh
+    """
+}
+
+private String getUbuntu14JvmPackagesBuildScript(final boolean useCuda, final boolean useOmp) {
+    return """
+        export JAVA_HOME=/usr/lib/jvm/java-8-oracle
         ${getBuildJARsOpts(useCuda, useOmp)} ./build_jars.sh
     """
 }
@@ -336,7 +371,7 @@ private void executeCheck(final String os, final String target, final String xgb
 private String getCheckScript(final String os, final String target) {
     switch (os) {
         case 'linux':
-            return getCentOS6CheckScript(target)
+            return getLinuxCheckScript(target)
         case 'osx':
             return getOSXCheckScript(target)
         default:
@@ -344,32 +379,26 @@ private String getCheckScript(final String os, final String target) {
     }
 }
 
-private String getCentOS6CheckScript(final String target) {
+private String getLinuxCheckScript(final String target) {
     final GString lddCmd = "ldd lib/linux_64/libxgboost4j_${target}.so"
     return """
-        ${lddCmd}
-        set +e
-        ${lddCmd} | grep -v 'libjvm.so => not found' | grep 'not found' > /dev/null
-        if [ \$? -eq 0 ]; then
+        ${lddCmd} &> ldd_check_${target}.log
+        if [ "\$(cat ldd_check_${target}.log | grep -v 'libjvm.so => not found' | grep 'not found')" ]; then
             echo "ldd check failed! Please check the following output:"
             ${lddCmd}
             exit 1
         fi
-        set -e
     """
 }
 
 private String getOSXCheckScript(final String target) {
     final GString otoolCmd = "otool -L lib/osx_64/libxgboost4j_${target}.dylib"
     return """
-        ${otoolCmd}
-        set +e
-        ${otoolCmd} | grep 'not' > /dev/null
-        if [ \$? -eq 0 ]; then
+        ${otoolCmd} &> ldd_check_${target}.log
+        if [ "\$(cat ldd_check_${target}.log | grep 'not')" ]; then
             echo "otool check failed! Please check the following output:"
             ${otoolCmd}
             exit 1
         fi
-        set -e
     """
 }
