[ITA-209] Unify handling of Linux as OS X

diff --git a/jvm-packages/jenkins/Jenkinsfile-Release b/jvm-packages/jenkins/Jenkinsfile-Release
--- a/jvm-packages/jenkins/Jenkinsfile-Release
+++ b/jvm-packages/jenkins/Jenkinsfile-Release
@@ -1,8 +1,9 @@
 @Library('test-shared-library@mr/ita/190-build-summary-emailer') _
 
-import ai.h2o.ci.buildsummary.StagesSummary
-import ai.h2o.ci.buildsummary.DetailsSummary
+
 import ai.h2o.ci.BuildResult
+import ai.h2o.ci.buildsummary.DetailsSummary
+import ai.h2o.ci.buildsummary.StagesSummary
 
 // initialize build summary
 buildSummary('https://github.com/h2oai/xgboost', true)
@@ -24,22 +25,35 @@ properties([
 
 BuildResult result = BuildResult.FAILURE
 
+final String dockerImage = "${REGISTRY}/opsh2oai/h2o-3-xgboost-build-${params.targetOS}"
 // configurations which will be built; the name is used also inside generated .jar,
 // for example the configuration with name 'gpu' will produce 'xgboost4j-native-linux_gpu-0.7.jar'
 final List CONFIGURATIONS = [
-        [name: 'minimal', useCuda: false, useOmp: false],
-        [name: 'omp', useCuda: false, useOmp: true],
-        [name: 'gpu', useCuda: true, useOmp: true],
+        [name: 'minimal', useCuda: false, useOmp: false, os: 'linux', dockerImage: dockerImage],
+        [name: 'omp', useCuda: false, useOmp: true, os: 'linux', dockerImage: dockerImage],
+        [name: 'gpu', useCuda: true, useOmp: true, os: 'linux', dockerImage: dockerImage],
+        [name: 'minimal', useCuda: false, useOmp: false, os: 'osx', node: 'osx'],
 ]
-final List CHECK_IMAGES = [
-        [name: 'CentOS 6', image: "${REGISTRY}/opsh2oai/h2o-3-xgboost-build-centos6"],
-        [name: 'Ubuntu', image: "${REGISTRY}/opsh2oai/h2o-3-runtime:107"]
+final Map CHECK_IMAGES = [
+        minimal: [
+                [name: 'CentOS 6', dockerImage: "${REGISTRY}/opsh2oai/h2o-3-xgboost-build-centos6", os: 'linux'],
+                [name: 'Ubuntu 16', dockerImage: "${REGISTRY}/opsh2oai/h2o-3-runtime:107", os: 'linux'],
+                [name: 'OS X', os: 'osx', node: 'osx']
+        ],
+        omp    : [
+                [name: 'CentOS 6', dockerImage: "${REGISTRY}/opsh2oai/h2o-3-xgboost-build-centos6", os: 'linux'],
+                [name: 'Ubuntu 16', dockerImage: "${REGISTRY}/opsh2oai/h2o-3-runtime:107", os: 'linux'],
+        ],
+        gpu    : [
+                [name: 'CentOS 6', dockerImage: "${REGISTRY}/opsh2oai/h2o-3-xgboost-build-centos6", os: 'linux'],
+                [name: 'Ubuntu 16', dockerImage: "${REGISTRY}/opsh2oai/h2o-3-runtime:107", os: 'linux'],
+        ]
+
 ]
-final String dockerImage = "${REGISTRY}/opsh2oai/h2o-3-xgboost-build-${params.targetOS}"
 
 // setup custom DetailsSummary
 DetailsSummary detailsSummary = new DetailsSummary()
-detailsSummary.setEntry(this, 'Build OS', params.targetOS)
+detailsSummary.setEntry(this, 'Build OS', "${params.targetOS} + OS X")
 detailsSummary.setEntry(this, 'Publish', params.publish ? 'Yes' : 'No')
 detailsSummary.setEntry(this, 'Docker image', dockerImage)
 buildSummary.get().addDetailsSummary(this, detailsSummary)
@@ -72,168 +86,137 @@ try {
                 git apply 01_dmlc_core_imports.patch
                 cd ..
             """
-            stash 'xgboost-osx-stash'
+            stash 'xgboost-sources'
         }
 
-        node('osx') {
-            buildSummary.stageWithSummary('Build MINIMAL with OS X') {
-                unstash 'xgboost-osx-stash'
+        CONFIGURATIONS.collect { config ->
+            buildSummary.stageWithSummary("Build ${config.name.toUpperCase()} with ${config.os}") {
                 try {
-                    sh """
-                        export JAVA_HOME=\$(/usr/libexec/java_home)
-    
-                        make clean_all
-                        
-                        mkdir -p build ci_build
-                        cd build
-                        
-                        cmake .. ${getCMakeOpts(false, false)}
-                        make 
-                        
-                        cd ../jvm-packages
-                        ./build_jars.sh
-                    """
-                    xgbVersion = sh(script: "(ls ${WORKSPACE}/jvm-packages/target/h2o | egrep -o [0-9]+.[0-9]+ | head -1)", returnStdout: true).trim()
-                    sh """
-                        cp jvm-packages/target/h2o/xgboost4j-native-osx-${xgbVersion}.jar ci_build/xgboost4j-native-osx_minimal-${xgbVersion}.jar
-                    """
-                    stash name: 'xgboost-osx-stash', includes: 'ci_build/*.jar'
+                    timeout(time: 60, unit: 'MINUTES') {
+                        if (config.node) {
+                            node(config.node) {
+                                try {
+                                    unstash 'xgboost-sources'
+                                    executeBuild(config)
+                                    stash name: "xgboost-${config.os}-artifacts", includes: 'ci_build/*.jar'
+                                } finally {
+                                    archiveArtifacts artifacts: 'ci_build/*.jar', allowEmptyArchive: true
+                                }
+                            }
+                        } else if (config.dockerImage) {
+                            docker.withRegistry("https://${REGISTRY}") {
+                                docker.image(config.dockerImage).inside("--init") {
+                                    executeBuild(config)
+                                }
+                            }
+                        } else {
+                            error "Configuration must specify either node or dockerImage"
+                        }
+                    }
                 } finally {
                     archiveArtifacts artifacts: 'ci_build/*.jar', allowEmptyArchive: true
                 }
             }
         }
 
-        error "NYI"
-
-//        CONFIGURATIONS.collect { config ->
-//            buildSummary.stageWithSummary("Build ${config.name.toUpperCase()} with ${params.targetOS}") {
-//                try {
-//                    timeout(time: 60, unit: 'MINUTES') {
-//                        docker.withRegistry("https://${REGISTRY}") {
-//                            docker.image(dockerImage).inside("--init") {
-//                                sh '''
-//                                    id
-//                                    printenv
-//                                '''
-//
-//                                sh """
-//                                    cd ${WORKSPACE}
-//
-//                                    make clean_all
-//
-//                                    mkdir -p build ci_build
-//                                    cd build
-//
-//                                    ${getBuildScript(config.useCuda, config.useOmp)}
-//
-//                                    cd ${WORKSPACE}/jvm-packages
-//                                    ${getJvmPackagesBuildScript(config.useCuda, config.useOmp)}
-//                                """
-//                                xgbVersion = sh(script: "(ls ${WORKSPACE}/jvm-packages/target/h2o | egrep -o [0-9]+.[0-9]+ | head -1)", returnStdout: true).trim()
-//                                sh """
-//                                    cd ${WORKSPACE}/jvm-packages
-//
-//                                    cp target/h2o/xgboost4j-${xgbVersion}.jar ${WORKSPACE}/ci_build/xgboost4j-${xgbVersion}.jar
-//                                    cp target/h2o/xgboost4j-native-linux-${xgbVersion}.jar ${WORKSPACE}/ci_build/xgboost4j-native-linux_${config.name}-${xgbVersion}.jar
-//                                """
-//                            }
-//                        }
-//                    }
-//                } finally {
-//                    archiveArtifacts artifacts: 'ci_build/*.jar', allowEmptyArchive: true
-//                }
-//            }
-//            CHECK_IMAGES.collect { image ->
-//                buildSummary.stageWithSummary("Check ${config.name.toUpperCase()} with ${image.name}") {
-//                    docker.image(image.image).inside("--init") {
-//                        sh """
-//                            cd ${WORKSPACE}/ci_build
-//                            echo "Checking for lib/linux_64/libxgboost4j_${config.name}.so"
-//                            rm -rf check
-//                            mkdir check
-//                            cp xgboost4j-native-linux_${config.name}-${xgbVersion}.jar check/xgboost4j-native-linux_${config.name}-${xgbVersion}.jar
-//                            cd check
-//                            unzip xgboost4j-native-linux_${config.name}-${xgbVersion}.jar
-//                            chmod +x lib/linux_64/libxgboost4j_${config.name}.so
-//                            ldd lib/linux_64/libxgboost4j_${config.name}.so
-//                            set +e
-//                            ldd lib/linux_64/libxgboost4j_${config.name}.so | grep -v 'libjvm.so => not found' | grep 'not found' > /dev/null
-//                            if [ \$? -eq 0 ]; then
-//                                echo "ldd check failed! Please check the following output:"
-//                                ldd lib/linux_64/libxgboost4j_${config.name}.so
-//                                exit 1
-//                            fi
-//                            set -e
-//                        """
-//                    }
-//                }
-//            }
-//        }
-
-        node('osx') {
-            buildSummary.stageWithSummary('Check MINIMAL with OS X') {
-                unstash 'xgboost-osx-stash'
-                sh """
-                    cd ci_build
-                    mkdir check
-                    cp xgboost4j-native-osx_minimal-${xgbVersion}.jar check
-                    cd check
-                    unzip xgboost4j-native-osx_minimal-${xgbVersion}.jarchmod +x lib/linux_64/libxgboost4j_${config.name}.so
-                    ldd lib/linux_64/libxgboost4j_minimal.so
-                    set +e
-                    ldd lib/linux_64/libxgboost4j_minimal.so | grep -v 'libjvm.so => not found' | grep 'not found' > /dev/null
-                    if [ \$? -eq 0 ]; then
-                        echo "ldd check failed! Please check the following output:"
-                        ldd lib/linux_64/libxgboost4j_minimal.so
-                        exit 1
-                    fi
-                    set -e
-
-                """
+        CHECK_IMAGES.each { target, checkConfigs ->
+            checkConfigs.collect { checkConfig ->
+                buildSummary.stageWithSummary("Check ${target} with ${checkConfig.name}") {
+                    if (checkConfig.node) {
+                        node(checkConfig.node) {
+                            unstash "xgboost-${checkConfig.os}-artifacts"
+                            executeCheck(checkConfig.os, target, xgbVersion)
+                        }
+                    } else if (checkConfig.dockerImage) {
+                        docker.withRegistry("https://${REGISTRY}") {
+                            docker.image(checkConfig.dockerImage).inside("--init") {
+                                executeCheck(checkConfig.os, target, xgbVersion)
+                            }
+                        }
+                    } else {
+                        error "Configuration must specify either node or dockerImage"
+                    }
+                }
             }
         }
 
-//        if (params.publish) {
-//            final String nexusIP = sh(script: 'dig +short nexus', returnStdout: true)
-//            docker.image(dockerImage).inside("--init --add-host=nexus:${nexusIP}") {
-//                withCredentials([file(credentialsId: 'local-nexus-settings-xml', variable: 'MAVEN_SETTINGS_PATH')]) {
-//                    sh """
-//                        mkdir -p ~/.m2
-//                        cp ${MAVEN_SETTINGS_PATH} ~/.m2/settings.xml
-//                    """
-//                }
-//                CONFIGURATIONS.eachWithIndex { config, index ->
-//                    buildSummary.stageWithSummary("Publish ${config.name.toUpperCase()}") {
-//                        sh """
-//                            export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-3.b14.el6_9.x86_64
-//                            cd ${WORKSPACE}/ci_build
-//                            mvn deploy:deploy-file -DgeneratePom=true -Dfile=xgboost4j-native-linux_${config.name}-${xgbVersion}.jar -Durl=${NEXUS_BASE_URL}/${REPO_URL} -DgroupId=ai.h2o -DartifactId=xgboost4j-native-linux_${config.name} -Dversion=0.7 -Dpackaging=jar -DrepositoryId=LocalNexus
-//                        """
-//                    }
-//                }
-//                buildSummary.stageWithSummary("Publish lib") {
-//                    sh """
-//                        cd ${WORKSPACE}/ci_build
-//                        export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-3.b14.el6_9.x86_64
-//
-//                        mvn deploy:deploy-file -DgeneratePom=true -Dfile=xgboost4j-${xgbVersion}.jar -Durl=${NEXUS_BASE_URL}/${REPO_URL} -DgroupId=ai.h2o -DartifactId=xgboost4j -Dversion=0.7 -Dpackaging=jar -DrepositoryId=LocalNexus
-//                    """
-//                }
-//            }
-//        }
+        if (params.publish) {
+            final String nexusIP = sh(script: 'dig +short nexus', returnStdout: true)
+            docker.image(dockerImage).inside("--init --add-host=nexus:${nexusIP}") {
+                withCredentials([file(credentialsId: 'local-nexus-settings-xml', variable: 'MAVEN_SETTINGS_PATH')]) {
+                    sh """
+                        mkdir -p ~/.m2
+                        cp ${MAVEN_SETTINGS_PATH} ~/.m2/settings.xml
+                    """
+                }
+                CONFIGURATIONS.eachWithIndex { config, index ->
+                    buildSummary.stageWithSummary("Publish ${config.os}-${config.name}") {
+                        if (config.os != 'linux') {
+                            unstash "xgboost-${config.os}-artifacts"
+                        }
+                        sh """
+                            export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-3.b14.el6_9.x86_64
+                            cd ${WORKSPACE}/ci_build
+                            mvn deploy:deploy-file -DgeneratePom=true -Dfile=xgboost4j-native-${config.os}_${config.name}-${xgbVersion}.jar -Durl=${NEXUS_BASE_URL}/${REPO_URL} -DgroupId=ai.h2o -DartifactId=xgboost4j-native-${config.os}_${config.name} -Dversion=0.7 -Dpackaging=jar -DrepositoryId=LocalNexus
+                        """
+                    }
+                }
+                buildSummary.stageWithSummary("Publish lib") {
+                    sh """
+                        cd ${WORKSPACE}/ci_build
+                        export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-3.b14.el6_9.x86_64
+
+                        mvn deploy:deploy-file -DgeneratePom=true -Dfile=xgboost4j-${xgbVersion}.jar -Durl=${
+                        NEXUS_BASE_URL
+                    }/${REPO_URL} -DgroupId=ai.h2o -DartifactId=xgboost4j -Dversion=0.7 -Dpackaging=jar -DrepositoryId=LocalNexus
+                    """
+                }
+            }
+        }
     }
     result = BuildResult.SUCCESS
 } finally {
     sendEmailNotif(result, buildSummary.get().toEmail(this), ['michalr@h2o.ai'])
 }
 
-private String getBuildScript(final boolean useCuda, final boolean useOmp) {
-    switch (params.targetOS) {
-        case 'centos6':
+private void executeBuild(final config) {
+    sh '''
+        id
+        printenv
+    '''
+
+    sh """
+        cd ${WORKSPACE}
+
+        make clean_all
+
+        mkdir -p build ci_build
+        cd build
+
+        ${getBuildScript(config.os, config.useCuda, config.useOmp)}
+
+        cd ${WORKSPACE}/jvm-packages
+        ${getJvmPackagesBuildScript(config.os, config.useCuda, config.useOmp)}
+    """
+    xgbVersion = sh(script: "(ls ${WORKSPACE}/jvm-packages/target/h2o | egrep -o [0-9]+.[0-9]+ | head -1)", returnStdout: true).trim()
+    sh """
+        cd ${WORKSPACE}/jvm-packages
+
+        cp target/h2o/xgboost4j-${xgbVersion}.jar ${WORKSPACE}/ci_build/xgboost4j-${xgbVersion}.jar
+        cp target/h2o/xgboost4j-native-${config.os}-${xgbVersion}.jar ${WORKSPACE}/ci_build/xgboost4j-native-${
+        config.os
+    }_${config.name}-${xgbVersion}.jar
+    """
+}
+
+private String getBuildScript(final String os, final boolean useCuda, final boolean useOmp) {
+    switch (os) {
+        case 'linux':
             return getCentOS6BuildScript(useCuda, useOmp)
+        case 'osx':
+            return getOSXBuildScript(useCuda, useOmp)
         default:
-            error "${params.targetOS} not supported"
+            error "OS ${os} not supported"
     }
 }
 
@@ -257,12 +240,23 @@ private String getCentOS6BuildScript(final boolean useCuda, final boolean useOmp
     """
 }
 
-private String getJvmPackagesBuildScript(final boolean useCuda, final boolean useOmp) {
-    switch (params.targetOS) {
-        case 'centos6':
+private String getOSXBuildScript(final boolean useCuda, final boolean useOmp) {
+    return """
+        export JAVA_HOME=\$(/usr/libexec/java_home)
+        
+        cmake .. ${getCMakeOpts(useCuda, useOmp)}
+        make
+    """
+}
+
+private String getJvmPackagesBuildScript(final String os, final boolean useCuda, final boolean useOmp) {
+    switch (os) {
+        case 'linux':
             return getCentOS6JvmPackagesBuildScript(useCuda, useOmp)
+        case 'osx':
+            return getOSXJvmPackagesBuildScript(useCuda, useOmp)
         default:
-            error "${params.targetOS} not supported"
+            error "OS ${os} not supported"
     }
 }
 
@@ -275,6 +269,13 @@ private String getCentOS6JvmPackagesBuildScript(final boolean useCuda, final boo
             echo "UNEXPECTED PYTHON VERSION"
             python --version
         fi
+        ${getBuildJARsOpts(useCuda, useOmp)} ./build_jars.sh
+    """
+}
+
+private String getOSXJvmPackagesBuildScript(final boolean useCuda, final boolean useOmp) {
+    return """
+        export JAVA_HOME=\$(/usr/libexec/java_home)
         ${getBuildJARsOpts(useCuda, useOmp)} ./build_jars.sh
     """
 }
@@ -301,4 +302,61 @@ private String getBuildJARsOpts(final boolean useCuda, final boolean useOmp) {
         opts += 'USE_OMP=TRUE'
     }
     return opts.join(' ')
+}
+
+private void executeCheck(final String os, final String target, final String xgbVersion) {
+    sh """
+        cd ${WORKSPACE}/ci_build
+        echo "Checking for lib/${os}_64/libxgboost4j_${target}.*"
+        rm -rf check
+        mkdir check
+        cp xgboost4j-native-${os}_${target}-${xgbVersion}.jar check/xgboost4j-native-${os}_${target}-${xgbVersion}.jar
+        cd check
+        unzip xgboost4j-native-${os}_${target}-${xgbVersion}.jar
+        chmod +x lib/${os}_64/libxgboost4j_${target}.*
+        
+        ${getCheckScript(os, target)}
+        
+    """
+}
+
+private String getCheckScript(final String os, final String target) {
+    switch (os) {
+        case 'linux':
+            return getCentOS6CheckScript(target)
+        case 'osx':
+            return getOSXCheckScript(target)
+        default:
+            error "OS ${os} not supported"
+    }
+}
+
+private String getCentOS6CheckScript(final String target) {
+    final GString lddCmd = "ldd lib/linux_64/libxgboost4j_${target}.so"
+    return """
+        ${lddCmd}
+        set +e
+        ${lddCmd} | grep -v 'libjvm.so => not found' | grep 'not found' > /dev/null
+        if [ \$? -eq 0 ]; then
+            echo "ldd check failed! Please check the following output:"
+            ${lddCmd}
+            exit 1
+        fi
+        set -e
+    """
+}
+
+private String getOSXCheckScript(final String target) {
+    final GString otoolCmd = "otool -L lib/osx_64/libxgboost4j_${target}.dylib"
+    return """
+        ${otoolCmd}
+        set +e
+        ${otoolCmd} | grep 'not' > /dev/null
+        if [ \$? -eq 0 ]; then
+            echo "otool check failed! Please check the following output:"
+            ${otoolCmd}
+            exit 1
+        fi
+        set -e
+    """
 }
